travis:
  secure:
    BINSTAR_TOKEN: d6bWSN4sqcU+lrBFL8vAK3losO2b49EJFbRVdCbiaFUK37wr+BG8WuQiL0CAZ0D+9CXoeAzHda15+zILgM4GQEHla6rRQ+mqxNurICcejpFlheunXRoDA2hOrXAvad2Xn7LJ6EM+WkJd6tBZPezrPdEYlTOu6rek9U2xi4PQS38vmrcvLptWoKxeInw27xG1sYWAds2J+9Kf6T71Omaz0PYafRbpv5adQb0WIUB8miFthiG82dkxNSuYfu3VMqyiuta6Syt4bwRDjmdpLTTEKYBbCXjicBtf5vVT9z6ORDhhN4lRx6vNlI3DBG79rcdzirIeVnqxw5KBCVX2Yz2Z+nokMq3KiXNCtfdSZ4STJCtJ96k0+tl81xgn0Mo1WwSfulFBTXvBqubgsG74sYgfQvbyAF/YesxhcCr4Z+auKgLyYaLEElUjqIUVaC4MkxwevS8ox4i2HA2GT/Vom0mxYDf5lRnpr81N9oEqITdjIi7sg2CXBELbpT8ZQN9k/utHLM8/rurPpfI/Pd0Q4TJe+kE7GSzszvf4dHnQHhmteuif5d/nLvSNKZDMhZ/BgmAxuP2D4Vu/w9euYm0tQCHbndb1g46/hDJQaGFh4nzGWoUxYfvBl1FM7baxF5OY9ECLGkk1t/mKXDXAqrWVPqCyWX2mLSfuA+y+s0glOwSgthE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
